[platformio]
data_dir = sim_fs

# ── ESP32 : firmware CTF (avec scénarios, flags, cron backdoor…) ──────────────
[env:MinitelOS]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
	symlink://../Minitel1B_Hard
	ewpa/LibSSH-ESP32
	marian-craciunescu/ESP32Ping
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
build_flags = -D CTF_MODE
build_src_filter = +<**/*.cpp> -<sim/**> -<native_main.cpp>

# ── ESP32 : firmware standard (sans CTF) ──────────────────────────────────────
[env:MinitelOS-standard]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
	symlink://../Minitel1B_Hard
	ewpa/LibSSH-ESP32
	marian-craciunescu/ESP32Ping
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
build_src_filter = +<**/*.cpp> -<sim/**> -<native_main.cpp>

# ── Simulateur natif : avec CTF ───────────────────────────────────────────────
[env:native]
platform = native
build_flags =
    -std=c++17
    -I sim/include
    -D NATIVE_SIM
    -D LITTLEFS_SIM_ROOT='"sim_fs"'
    -D CTF_MODE
    -lcurl
build_src_filter = +<**/*.cpp> -<main.cpp>
lib_ldf_mode = deep+

# ── Simulateur natif : sans CTF ───────────────────────────────────────────────
[env:native-standard]
platform = native
build_flags =
    -std=c++17
    -I sim/include
    -D NATIVE_SIM
    -D LITTLEFS_SIM_ROOT='"sim_fs"'
    -lcurl
build_src_filter = +<**/*.cpp> -<main.cpp>
lib_ldf_mode = deep+